# Generated by Django 3.2.3 on 2021-05-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('localization', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.sensor')),
            ],
        ),
    ]
