# Generated by Django 3.2.3 on 2021-05-31 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_hypertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.FloatField(),
        ),
    ]
