# Generated by Django 3.2.3 on 2021-06-17 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_measurement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 0, 10, 16, 910247, tzinfo=utc), primary_key=True, serialize=False),
        ),
    ]
