# Generated by Django 3.2.3 on 2021-06-17 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 0, 29, 40, 360953), primary_key=True, serialize=False),
        ),
    ]
