# Generated by Django 3.2.3 on 2021-06-17 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 0, 30, 58, 334379, tzinfo=utc), primary_key=True, serialize=False),
        ),
    ]
